"""Convert kuno-sprites.png into C64 hardware sprite data."""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


class PhaseOutOfBoundsError(ValueError):
    """A phase position is outside the source image."""


class DuplicateSlotError(ValueError):
    """Two phases share the same slot."""


class SlotOutOfRangeError(ValueError):
    """A phase slot is >= total_slots."""


@dataclass(frozen=True)
class Phase:
    name: str
    slot: int
    pos: tuple[int, int]
    color: int


@dataclass(frozen=True)
class Config:
    source_image: Path
    output_bin: Path
    output_inc: Path
    preview_built: Path
    sprite_size: tuple[int, int]
    slot_bytes: int
    threshold: int
    sprite_index_base: int
    total_slots: int
    phases: tuple[Phase, ...]


def load_config(config_path: Path) -> Config:
    """Load and validate a sprite_phases.json from disk.

    Paths in the JSON are resolved relative to the config file's directory.
    Raises DuplicateSlotError, SlotOutOfRangeError, FileNotFoundError.
    """
    config_path = Path(config_path)
    with config_path.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    base_dir = config_path.parent
    source = (base_dir / raw["source_image"]).resolve()
    if not source.exists():
        raise FileNotFoundError(f"source_image not found: {source}")

    phases = tuple(
        Phase(
            name=p["name"],
            slot=p["slot"],
            pos=tuple(p["pos"]),
            color=p["color"],
        )
        for p in raw["phases"]
    )

    total = raw["total_slots"]
    seen_slots: dict[int, str] = {}
    for ph in phases:
        if ph.slot >= total or ph.slot < 0:
            raise SlotOutOfRangeError(
                f"phase {ph.name!r} has slot {ph.slot}, must be in [0, {total})"
            )
        if ph.slot in seen_slots:
            raise DuplicateSlotError(
                f"slot {ph.slot} used by {seen_slots[ph.slot]!r} and {ph.name!r}"
            )
        seen_slots[ph.slot] = ph.name

    return Config(
        source_image=source,
        output_bin=(base_dir / raw["output_bin"]).resolve(),
        output_inc=(base_dir / raw["output_inc"]).resolve(),
        preview_built=(base_dir / raw["preview_built"]).resolve(),
        sprite_size=tuple(raw["sprite_size"]),
        slot_bytes=raw["slot_bytes"],
        threshold=raw["threshold"],
        sprite_index_base=raw["sprite_index_base"],
        total_slots=total,
        phases=phases,
    )


def pack_phase(image: Image.Image, threshold: int) -> bytes:
    """Pack a 24x21 RGBA image into 64 bytes of C64 hires sprite data.

    Layout: each row uses 3 bytes (24 bits), MSB-first. Row y starts at
    byte y*3. The 64th byte is slot padding (always 0). A pixel is
    foreground when alpha > 0 AND (R+G+B)/3 < threshold.
    """
    if image.size != (24, 21):
        raise ValueError(f"expected 24x21 image, got {image.size}")
    out = bytearray(64)
    for y in range(21):
        for x in range(24):
            r, g, b, a = image.getpixel((x, y))
            if a > 0 and (r + g + b) // 3 < threshold:
                byte_idx = y * 3 + x // 8
                bit_idx = 7 - (x % 8)
                out[byte_idx] |= 1 << bit_idx
    return bytes(out)


def build_bin(cfg: Config) -> bytes:
    """Read source PNG and produce total_slots * slot_bytes of sprite data."""
    src = Image.open(cfg.source_image).convert("RGBA")
    sw, sh = src.size
    pw, ph = cfg.sprite_size

    out = bytearray(cfg.total_slots * cfg.slot_bytes)
    for phase in cfg.phases:
        x, y = phase.pos
        if x < 0 or y < 0 or x + pw > sw or y + ph > sh:
            raise PhaseOutOfBoundsError(
                f"phase {phase.name!r} at ({x},{y}) extends past image "
                f"({sw}x{sh}) with sprite_size ({pw}x{ph})"
            )
        crop = src.crop((x, y, x + pw, y + ph))
        packed = pack_phase(crop, cfg.threshold)
        offset = phase.slot * cfg.slot_bytes
        out[offset : offset + cfg.slot_bytes] = packed
    return bytes(out)


def build_inc(cfg: Config) -> str:
    """Generate TRSE-Pascal @define lines, one per configured phase."""
    lines = [
        "// AUTO-GENERATED by tools/sprites/build_c64_sprites.py",
    ]
    name_width = max((len(p.name) for p in cfg.phases), default=0)
    for phase in sorted(cfg.phases, key=lambda p: p.slot):
        idx = cfg.sprite_index_base + phase.slot
        upper = phase.name.upper()
        lines.append(f"@define {upper:<{name_width}}  {idx}")
    return "\n".join(lines) + "\n"


# C64-Farbpalette (Approximationen der Hardware-Farben für die Vorschau)
C64_PALETTE = {
    0:  (0, 0, 0),         # black
    1:  (255, 255, 255),   # white
    2:  (136, 0, 0),       # red
    3:  (170, 255, 238),   # cyan
    4:  (204, 68, 204),    # purple
    5:  (0, 204, 85),      # green
    6:  (0, 0, 170),       # blue
    7:  (238, 238, 119),   # yellow
    8:  (221, 136, 85),    # orange
    9:  (102, 68, 0),      # brown
    10: (255, 119, 119),   # light red
    11: (51, 51, 51),      # dark grey
    12: (119, 119, 119),   # mid grey
    13: (170, 255, 102),   # light green
    14: (0, 136, 255),     # light blue
    15: (187, 187, 187),   # light grey
}


def render_preview(cfg: Config, bin_data: bytes) -> Image.Image:
    """Decode .bin slots back to a labelled grid PNG using each phase's color."""
    pw, ph_h = cfg.sprite_size
    scale = 4
    cols = 7
    rows = (len(cfg.phases) + cols - 1) // cols
    pad_x, pad_y = 16, 50
    cell_w = pw * scale + pad_x
    cell_h = ph_h * scale + pad_y
    canvas_w = cell_w * cols + pad_x
    canvas_h = cell_h * rows + pad_y

    canvas = Image.new("RGB", (canvas_w, canvas_h), (40, 40, 50))
    sorted_phases = sorted(cfg.phases, key=lambda p: p.slot)

    for i, phase in enumerate(sorted_phases):
        offset = phase.slot * cfg.slot_bytes
        slot_bytes = bin_data[offset : offset + cfg.slot_bytes]
        sprite_img = Image.new("RGB", (pw, ph_h), (255, 255, 255))
        fg = C64_PALETTE.get(phase.color, (0, 0, 0))
        for y in range(ph_h):
            for x in range(pw):
                byte = slot_bytes[y * 3 + x // 8]
                if byte & (1 << (7 - (x % 8))):
                    sprite_img.putpixel((x, y), fg)
        big = sprite_img.resize((pw * scale, ph_h * scale), Image.NEAREST)
        gx = (i % cols) * cell_w + pad_x
        gy = (i // cols) * cell_h + pad_y
        canvas.paste(big, (gx, gy))

    return canvas


def main() -> None:
    config_path = Path(__file__).parent / "sprite_phases.json"
    cfg = load_config(config_path)

    bin_data = build_bin(cfg)
    inc_text = build_inc(cfg)

    cfg.output_bin.parent.mkdir(parents=True, exist_ok=True)
    cfg.output_bin.write_bytes(bin_data)
    cfg.output_inc.write_text(inc_text, encoding="utf-8")

    cfg.preview_built.parent.mkdir(parents=True, exist_ok=True)
    preview = render_preview(cfg, bin_data)
    preview.save(cfg.preview_built)

    print(f"Wrote {cfg.output_bin} ({len(bin_data)} bytes)")
    print(f"Wrote {cfg.output_inc}")
    print(f"Wrote {cfg.preview_built}")


if __name__ == "__main__":
    main()
