/***************************************************************************/
/* Farbcode und Bewegungsphasen des Editor-Cursors                         */
/***************************************************************************/
unsigned char CURSOR1 [24*21];
unsigned char CURSOR11[24*21];
unsigned char CURSOR12[24*21];
unsigned char CURSOR13[24*21];
unsigned char CURSOR2 [24*21];
unsigned char CURSOR21[24*21];
unsigned char CURSOR22[24*21];
unsigned char CURSOR23[24*21];
